### ISSUE TITLE
[UX] Wrap option to use Elysia cron in module_exists()

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/backup_migrate#28]
I'm not using the elysia cron module, yet on the settings page for Backup and migrate I still see the option "Run using Elysia cron". This option should only appear if that module is installed and enabled, otherwise it clutters the UI and creates a less-than-ideal user experience.

**Comment by robertgarrigos** [comment]
@jenlampton I'm just looking at this because the settings were actually unaccessible (there is a 
 PR (https://github.com/backdrop-contrib/backup_migrate/pull/30) for that) and what I see right now is a dimmed option for elysia cron, which I find actually useful. Its a way of saying "I can work with elysia cron". It could be said with just a text line. Either way, with a module_exists() wrap you would never know you can use it.

**Comment by jenlampton** [comment]
It's ultimately up to you, but my point was that people who are not using the Elysia cron module won't understand what it means, and even if they do, they won't care that the option exists. For them, seeing the setting creates clutter and confusion, leading to a poorer user experience. 

If Elysia cron was a core module or a module used by more than 80% of Backdrop users, it would make sense to display the option all the time since the majority of people would benefit from seeing it. However, since this is a setting only for the minority of users, it would be more inline with Backdrop's principles create a better user experience for the majority by hiding it, and show it only for those who actually need it.

**Comment by Wylbur** [comment]
I checked and this does not appear to be an issue any longer.  Can this be closed?

**Comment by quackers8me** [comment]
@Wylbur yes, this can be closed. Thank-you.
