### ISSUE TITLE
[UX] what's the difference between "Add schedule" and "Create a new schedule"?

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/backup_migrate#38]
On the schedules tab there's both an action link, and a link at the bottom of the page to `Create a new schedule`. Do these both do the same thing? If so, what's the reason for the non-action link version? Can it be removed? 
<img width="1190" alt="screen shot 2018-03-30 at 3 09 03 pm" src="https://user-images.githubusercontent.com/397895/38155439-a2a774f6-342c-11e8-8fcd-99190d89b7d8.png">

**Comment by argiepiano** [comment]
They do the same thing. Apparently they were added at different points in time to the D7 version, and the developers forgot to remove them (the bottom one is older). They are still present in the D7 version.

EDIT: the one in the bottom is needed when viewing the summary page (Settings), because that page contains all of the sources, destinations and profiles, and doesn't show the local action links.

**Comment by argiepiano** [comment]
PR #89 removes the bottom duplicate when the local action is shown.

**Comment by argiepiano** [comment]
Reopening while people test this.

**Comment by argiepiano** [comment]
Closing now that this PR is included in version 1-x.1.0.23
