### ISSUE TITLE
Re-add tests

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/backup_migrate#54]
The Drupal 7 version has tests, we should include them and make them work for Backdrop.

**Comment by argiepiano** [comment]
Working on this. However, I'd like to update the module to its current D7 state before bringing back the tests. The current version is based on a D7 version from 3 or 4 years ago, and it has never been updated. Working on several updates in #91. 

It'd be great to get people to test all the PRs I've added in the last 2 days.

**Comment by argiepiano** [comment]
@herbdool I've added all relevant tests (minus CTools tests) to a major overhaul PR that adds several features from the D7 later releases in #91. I'm going to close this issue here since tests have been added there. The PR hasn't yet added an automated GH action to run those - I've been running them manually. I will add that soon too. 

It'd be great if you could test some of these new features.
